### ISSUE TITLE
I Can't PR... it automatically got deleted so check this

### ISSUE THREAD

**Issue by starterdragon** [Adam1609/MysUPets#14]
-   public function onPlayerQuit(player $player) {
-   public function clearPet(player $player) {
      $player->getPlayer();
      $pet = $player->getPet();
      if (!is_null($pet)) {
          $this->disablePet($player);
      }
  }
  //test clear pets
-   public function Clearpet(PlayerQuitEvent $event) {
-   public function onPlayerQuit(PlayerQuitEvent $event) {
      $player = $event->getPlayer();
      $pet = $player->getPet();
      if (!is_null($pet)) {

@main.php

**Comment by Adam1609** [comment]
We are working to fix it. Please wait until it's completely done!

**Comment by Adam1609** [comment]
I have merged. Closed.
