### ISSUE TITLE
command not working

### ISSUE THREAD

**Issue by kabluinc** [Adam1609/MysUPets#16]
i tryed /pets and /pets type wolf but nothing happens

please help

**Comment by Adam1609** [comment]
The command to summon, I forgot, please wait until this plugin is done!

**Comment by kabluinc** [comment]
Fixed. 
after removing the permissions from plugin.yml the commands to summon, disappear and spawn a entity type is working again. the permission nodes are already written in the plugin code which is in the commands folder so no need to write them again in plugin.yml. doing so stops the plugins commands from working.

**Comment by kabluinc** [comment]
I can submit a pull request for the plugin.yml and petcommands.php which I have modified to make the commands work and allow a permission for the summoning

**Comment by Adam1609** [comment]
Ok, as long as this plugin works, I will be greatful to have your support, thanks

**Comment by XakerS** [comment]
Creat pull request pls :-)

**Comment by Adam1609** [comment]
we have a big support and it is working ,thanks !
