### ISSUE TITLE
Taken from LBCore

### ISSUE THREAD

**Issue by remotevase** [Adam1609/MysUPets#20]
This plugin was taken from lifeboat's lbcore as it says
use lbcore\player\lbplayer

**Comment by Adam1609** [comment]
Yes, It was taken to Lbcore, but I asked credit to YaBoiBalAnce so....

**Comment by Adam1609** [comment]
and I try to ask permission but seem doesn't online at that time so...

**Comment by remotevase** [comment]
Okay, please add lbcore credits to on forums and readme because lbsg had a license and stolen code ruins it

**Comment by Adam1609** [comment]
Okay, sorry for that, I will keep doing this kind of plugin.

**Comment by remotevase** [comment]
Okay
