### ISSUE TITLE
Please fix,plugins not working :/

### ISSUE THREAD

**Issue by XakerS** [Adam1609/MysUPets#8]
Do not respond to Commands / pets & pet

**Comment by XakerS** [comment]
-_-

**Comment by XakerS** [comment]
You'll Fix?

**Comment by Adam1609** [comment]
Fixed! You can download it, maybe it contains some bug but this plugin has permission

**Comment by XakerS** [comment]
Do you have your own server?

**Comment by XakerS** [comment]
Fix..command and now do not work

**Comment by Adam1609** [comment]
Of course I have my own server, you can go on and check:
Sorry they r all vietnamese so i can help you through console
mysu.hopto.org Port 19132

**Comment by Adam1609** [comment]
I will try fix this Pets summon, you can type /pets type (entities) instead

**Comment by XakerS** [comment]
Thank you for your work in the development of this plugin :)

**Comment by XakerS** [comment]
Are you registered in vk.com?

**Comment by Adam1609** [comment]
No I don't. I don't know VK :(

**Comment by XakerS** [comment]
Do you want to meet him? VK top russian social network :) And there are a lot of interesting things including the Russian developers.

**Comment by Adam1609** [comment]
Sure, please help me!

**Comment by XakerS** [comment]
There's no registration trudno.Posle write me a message there will be easier to explain what's what.
Profile: vk.com/mcg76

**Comment by XakerS** [comment]
Trudno = hard*

**Comment by Adam1609** [comment]
it is working, thanks you !
